### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by mambax7** [geekwright/surnames#1]
When I go to: /modules/system/admin.php?fct=modulesadmin&op=installlist
I'm getting:
Error: Error: Call to a member function checkRight() on null in file /class/libraries/vendor/xoops/xmf/src/Xmf/Module/Helper/Permission.php line 71

It's called from: xoops_version.php
```php
if ($permHelper->checkPermission('surnames_approve', 2)) {
    $modversion['sub'][] = array(
        'name' => _MI_SURNAMES_MENU_REVIEW,
        'url' => 'review.php',
    );
```

The problem is that the $permHelper is never initialized:
```php
        if (is_object($this->module)) {
            $this->init();
        }
```
because the module itself is not yet installed.

**Comment by mambax7** [comment]
How about changing the function checkPermission() to: 

```php
    public function checkPermission($gperm_name, $gperm_itemid, $trueifadmin = true)
    {
        $ret           = false;
        $gperm_itemid  = (int)$gperm_itemid;
        $gperm_groupid = $this->getUserGroups();
        if (is_object($this->permissionHandler)) {
            $ret = $this->permissionHandler->checkRight($gperm_name, $gperm_itemid, $gperm_groupid, $this->mid, (bool)$trueifadmin);
        }
        return $ret;
    }
```

**Comment by geekwright** [comment]
Fixed. That was really sloppy of me :man_facepalming: 

That is an serious error condition, not really something something we should just overlook.If the permission helper doesn't have a module to work with, it can't do anything useful.  I'll look at making it more intentionally handled, like an Exception. 

The base problem in this case was that the sub menu items were always being added, not only when the module wasn't active, but when it wasn't installed, too. Before its XMF conversion that must have quietly failed in some other way.

Looking forward, in 2.6 those item definitions have been moved out of xoops_version, but for now the programmer needs to guard against it.

**Comment by mambax7** [comment]
I ran into a similar issue before but with the module helper, so originally I used this code to at least have a helper:
```php
if (false !== ($moduleHelper = Xmf\Module\Helper::getHelper($moduleDirName))) {
} else {
    $moduleHelper = Xmf\Module\Helper::getHelper('system');
}
```
but now I am adding to every module a helper class extending \Xmf\Module\Helper, so I can get around it, something like this
```php
class RepairshopHelper   extends \Xmf\Module\Helper
{
    public $debugArray = [];

    /**
     * @internal param $debug
     */
    protected function __construct()
    {
        //        $this->debug   = $debug;
        $this->dirname = basename(dirname(__DIR__));
    }

    /**
     * @param bool $debug
     *
     * @return RepairshopHelper
     */
    public static function getInstance($debug = false)
    {
        static $instance;
        if (null === $instance) {
            $instance = new static($debug);
        }

        return $instance;
    }
}
```
